# Generated by Django 3.2.8 on 2022-01-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_icom',
            new_name='service_icon',
        ),
    ]
